### ISSUE TITLE
百度小程序所有图片都不显示

### ISSUE THREAD

**Issue by qq1311256696** [EasyTuan/taro-msparis#11]
百度小程序所有和图片有关的都不显示
![1](https://user-images.githubusercontent.com/30926001/48539295-ab176680-e8f1-11e8-9cf8-fe2a2cd9a5ff.png)

**Comment by EasyTuan** [comment]
我这边都是正常显示的，请按issuse规范把问题具体化一下，方便我这边重现

**Comment by qq1311256696** [comment]
我自己调好了，在百度小程序中ClothingsItem中的列表父元素宽高会变成0，得给父元素加一个宽高就好了

**Comment by EasyTuan** [comment]
好的
