### ISSUE TITLE
h5页面运行正常，小程序运行报错

### ISSUE THREAD

**Issue by SubinY** [EasyTuan/taro-msparis#22]
**问题描述**
h5页面运行正常，小程序运行报错
![image](https://user-images.githubusercontent.com/21135159/49569200-3f636f00-f96e-11e8-9c86-87610a613d74.png)

**复现步骤**
[复现问题的步骤]
1. npm run dev:weapp
2. open the wx web client-side

**期望行为**
不是appid的问题，我重新一一检视过appid是否一致

**系统信息**

 - Taro 版本  1.1.8
 - Node.js 版本 8.9.4
 - 报错平台 weapp

**补充信息**
不是appid的问题，我重新一一检视过appid是否一致

**Comment by EasyTuan** [comment]
报错信息已经明确说了，请求域名不在域名列表，在小程序后台添加下白名单
