### ISSUE TITLE
npm run dev:h5 白屏

### ISSUE THREAD

**Issue by neuyu** [EasyTuan/taro-msparis#26]
**问题描述**

npm run dev:h5 出现白屏

**复现步骤**
1. npm run dev:h5
2. See error

**报错信息**

![image](https://user-images.githubusercontent.com/16551927/49773276-6681be00-fd2b-11e8-8685-9412e049336c.png)

**系统信息**

 - 操作系统: [e.g. macOS 10.12]
 - Taro 版本 [e.g. v.1.2.0-beta.11]
 - Node.js 版本 [e.g. v10.11.0]
 - 报错平台 [h5]
 - 浏览器 [Chrome 72.0.3626.7]

**Comment by EasyTuan** [comment]
我这边是正常的，检查下配置和依赖性

**Comment by EasyTuan** [comment]
我试了下bata版本的确有问题，暂时先退回稳定版本
`
npm install -g @tarojs/cli@1.1.9
`

**Comment by EasyTuan** [comment]
把项目依赖也升级到最新
`
taro update project
`

**Comment by neuyu** [comment]
thanks
