### ISSUE TITLE
编译出现error

### ISSUE THREAD

**Issue by gh357550318** [EasyTuan/taro-msparis#39]
ESLint(null) 错误：Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

   7 |   ...user,
   8 | }))
>  9 | export default class User extends Component {
     | ^
  10 |   config = {
  11 |     navigationBarTitleText: 'user',
  12 |   };
-----

**Comment by 1076momo** [comment]
eslint不允许这么写，其实也没啥影响，不想要这个警告解决方案如下：
class User extends Component {
   ....
}
export default User;
