### ISSUE TITLE
npm run dev:h5 error

### ISSUE THREAD

**Issue by Aopodo** [EasyTuan/taro-msparis#6]
`taro-msparis git:(master) ✗ npm run dev:h5

> taro-msparis@1.0.0 dev:h5 /Users/*/taro-msparis
> npm run build:h5 -- --watch

> taro-msparis@1.0.0 build:h5 /Users/*/taro-msparis
> taro build --type h5 "--watch"

sh: taro: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! taro-msparis@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the taro-msparis@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aopodo/.npm/_logs/2018-11-07T16_45_30_767Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro-msparis@1.0.0 dev:h5: `npm run build:h5 -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taro-msparis@1.0.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aopodo/.npm/_logs/2018-11-07T16_45_30_785Z-debug.log`

兄弟，为啥我没有taro command？

**Comment by EasyTuan** [comment]
执行下  npm install -g @tarojs/cli 全局安装下taro脚手架工具

**Comment by Aopodo** [comment]
ok, it's work
